version: '3.1'

services:
  postgres:
    command: '-p ${TYPEORM_PORT}'
    container_name: '${POSTGRES_CONTAINER_NAME}'
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${TYPEORM_DATABASE}'
      POSTGRES_USER: '${TYPEORM_USERNAME}'
      POSTGRES_PASSWORD: '${TYPEORM_PASSWORD}'
      TZ: '${DB_TIMEZONE}'
      PGTZ: '${DB_TIMEZONE}'
    image: 'postgres:11.5'
    ports:
      - '${TYPEORM_PORT}:${POSTGRES_SHARE_PORT}'
    restart: always
    volumes:
      - '${POSTGRES_VOLUME}'
  redis:
    container_name: support_redis
    image: redis:alpine
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:${REDIS_PORT}
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - '${REDIS_VOLUME}'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
